version: '2'
services:
  etcd:
    container_name: etcd_node01
    image: quay.io/coreos/etcd:v3.5.3
    network_mode: "host"
    restart: always
    command:
      /usr/local/bin/etcd
      -name etcd_node01
      -initial-cluster-state new
      -advertise-client-urls http://$NODE01_IP:2379
      -initial-advertise-peer-urls http://$NODE01_IP:2380
      -listen-peer-urls http://$NODE01_IP:2380
      -listen-client-urls http://$NODE01_IP:2379,http://127.0.0.1:2379
      -data-dir /etcd-data
      -heartbeat-interval=250
      -election-timeout=1250
      -auto-compaction-retention=12
      -enable-v2=true
      -auto-tls=false
      -peer-auto-tls=false
      -enable-pprof=false
      -metrics=basic
      -auth-token=simple
      #-force-new-cluster=false
    healthcheck:
      test: etcdctl endpoint status
      interval: 1m
      timeout: 10s
      retries: 5
    volumes:
      - "./data:/etcd-data"
