version: "3"
services:
  haproxy:
    build: ..
    container_name: haproxy_node01
    network_mode: host
    healthcheck:
      test: curl http://$NODE01_IP:8888/health
      interval: 1m
      timeout: 10s
      retries: 5
    volumes:
      - "../haproxy.cfg://usr/local/etc/haproxy/haproxy.cfg"
    restart: always
